import type { TowerDef } from '../types/tower';

export const BASE_TOWERS: TowerDef[] = [
  {
    id: 'laser',
    name: '궁수 탑',
    type: 'laser',
    tier: 1,
    stats: { damage: 10, range: 3, attackSpeed: 1.5 },
    cost: 50,
    isPremium: false,
    color: '#c8a04a',
    shape: 'diamond',
  },
  {
    id: 'plasma',
    name: '투석기',
    type: 'plasma',
    tier: 1,
    stats: { damage: 25, range: 2, attackSpeed: 0.8, special: 'splash' },
    cost: 80,
    isPremium: false,
    color: '#8b4513',
    shape: 'hexagon',
  },
  {
    id: 'emp',
    name: '서리 마탑',
    type: 'emp',
    tier: 1,
    stats: { damage: 5, range: 4, attackSpeed: 1.0, special: 'slow_30%' },
    cost: 60,
    isPremium: false,
    color: '#5bc8e8',
    shape: 'circle',
  },
  {
    id: 'shield',
    name: '성기사 제단',
    type: 'shield',
    tier: 1,
    stats: { damage: 0, range: 2, attackSpeed: 0, special: 'boost_adjacent_20%' },
    cost: 70,
    isPremium: false,
    color: '#f0e080',
    shape: 'shield',
  },
];

export const FUSION_TOWERS: TowerDef[] = [
  {
    id: 'twin_laser',
    name: '쌍궁 탑',
    type: 'twin_laser',
    tier: 2,
    stats: { damage: 25, range: 4, attackSpeed: 2.0 },
    cost: 0,
    fusionRecipe: ['laser', 'laser'],
    isPremium: false,
    color: '#c8a04a',
    shape: 'star',
  },
  {
    id: 'disruptor',
    name: '눈보라 탑',
    type: 'disruptor',
    tier: 2,
    stats: { damage: 15, range: 5, attackSpeed: 1.2, special: 'slow_50%_splash' },
    cost: 0,
    fusionRecipe: ['emp', 'plasma'],
    isPremium: false,
    color: '#5bc8e8',
    shape: 'star',
  },
  {
    id: 'nova_cannon',
    name: '공성 대포',
    type: 'nova_cannon',
    tier: 2,
    stats: { damage: 60, range: 3, attackSpeed: 0.4, special: 'aoe_2tile' },
    cost: 0,
    fusionRecipe: ['plasma', 'plasma'],
    isPremium: false,
    color: '#8b4513',
    shape: 'star',
  },
  {
    id: 'fortress',
    name: '수호 탑',
    type: 'fortress',
    tier: 2,
    stats: { damage: 15, range: 3, attackSpeed: 1.0, special: 'boost_adjacent_40%' },
    cost: 0,
    fusionRecipe: ['shield', 'laser'],
    isPremium: false,
    color: '#f0e080',
    shape: 'star',
  },
  {
    id: 'stasis_field',
    name: '빙하 제단',
    type: 'stasis_field',
    tier: 2,
    stats: { damage: 0, range: 3, attackSpeed: 0, special: 'freeze_2s_cooldown_8s' },
    cost: 0,
    fusionRecipe: ['emp', 'shield'],
    isPremium: false,
    color: '#a8def0',
    shape: 'star',
  },
];

export const ALL_TOWERS: TowerDef[] = [...BASE_TOWERS, ...FUSION_TOWERS];
