import type { TowerDef } from '../types/tower';

export const BASE_TOWERS: TowerDef[] = [
  {
    id: 'laser',
    name: '레이저 터렛',
    type: 'laser',
    tier: 1,
    stats: { damage: 10, range: 3, attackSpeed: 1.5 },
    cost: 50,
    isPremium: false,
    color: '#e2b714',
    shape: 'diamond',
  },
  {
    id: 'plasma',
    name: '플라즈마 캐논',
    type: 'plasma',
    tier: 1,
    stats: { damage: 25, range: 2, attackSpeed: 0.8, special: 'splash' },
    cost: 80,
    isPremium: false,
    color: '#2cb67d',
    shape: 'hexagon',
  },
  {
    id: 'emp',
    name: 'EMP 방전기',
    type: 'emp',
    tier: 1,
    stats: { damage: 5, range: 4, attackSpeed: 1.0, special: 'slow_30%' },
    cost: 60,
    isPremium: false,
    color: '#7f5af0',
    shape: 'circle',
  },
  {
    id: 'shield',
    name: '쉴드 생성기',
    type: 'shield',
    tier: 1,
    stats: { damage: 0, range: 2, attackSpeed: 0, special: 'boost_adjacent_20%' },
    cost: 70,
    isPremium: false,
    color: '#00ccff',
    shape: 'shield',
  },
];

export const FUSION_TOWERS: TowerDef[] = [
  {
    id: 'twin_laser',
    name: '트윈 레이저',
    type: 'twin_laser',
    tier: 2,
    stats: { damage: 25, range: 4, attackSpeed: 2.0 },
    cost: 0,
    fusionRecipe: ['laser', 'laser'],
    isPremium: false,
    color: '#e2b714',
    shape: 'star',
  },
  {
    id: 'disruptor',
    name: '디스럽터',
    type: 'disruptor',
    tier: 2,
    stats: { damage: 15, range: 5, attackSpeed: 1.2, special: 'slow_50%_splash' },
    cost: 0,
    fusionRecipe: ['emp', 'plasma'],
    isPremium: false,
    color: '#7f5af0',
    shape: 'star',
  },
  {
    id: 'nova_cannon',
    name: '노바 캐논',
    type: 'nova_cannon',
    tier: 2,
    stats: { damage: 60, range: 3, attackSpeed: 0.4, special: 'aoe_2tile' },
    cost: 0,
    fusionRecipe: ['plasma', 'plasma'],
    isPremium: false,
    color: '#2cb67d',
    shape: 'star',
  },
  {
    id: 'fortress',
    name: '포트리스',
    type: 'fortress',
    tier: 2,
    stats: { damage: 15, range: 3, attackSpeed: 1.0, special: 'boost_adjacent_40%' },
    cost: 0,
    fusionRecipe: ['shield', 'laser'],
    isPremium: false,
    color: '#00ccff',
    shape: 'star',
  },
  {
    id: 'stasis_field',
    name: '정체장',
    type: 'stasis_field',
    tier: 2,
    stats: { damage: 0, range: 3, attackSpeed: 0, special: 'freeze_2s_cooldown_8s' },
    cost: 0,
    fusionRecipe: ['emp', 'shield'],
    isPremium: false,
    color: '#94a1b2',
    shape: 'star',
  },
];

export const ALL_TOWERS: TowerDef[] = [...BASE_TOWERS, ...FUSION_TOWERS];
