import type { TowerDef } from '../types/tower';

// T1 Common (4 towers)
export const BASE_TOWERS: TowerDef[] = [
	{
		id: 'archer',
		name: '궁수 탑',
		type: 'archer',
		tier: 1,
		stats: { damage: 10, range: 3, attackSpeed: 1.5 },
		cost: 10,
		element: 'neutral',
		isPremium: false,
		color: '#c8a04a',
		shape: 'diamond',
	},
	{
		id: 'plasma',
		name: '투석기',
		type: 'plasma',
		tier: 1,
		stats: { damage: 25, range: 2, attackSpeed: 0.8, special: 'splash' },
		cost: 10,
		element: 'neutral',
		isPremium: false,
		color: '#8b4513',
		shape: 'hexagon',
	},
	{
		id: 'emp',
		name: '서리 마탑',
		type: 'emp',
		tier: 1,
		stats: { damage: 5, range: 4, attackSpeed: 1.0, special: 'slow_30%' },
		cost: 20,
		element: 'water',
		isPremium: false,
		color: '#5bc8e8',
		shape: 'circle',
	},
	{
		id: 'shield',
		name: '성기사 제단',
		type: 'shield',
		tier: 1,
		stats: {
			damage: 0,
			range: 2,
			attackSpeed: 0,
			special: 'stun',
		},
		cost: 20,
		element: 'neutral',
		isPremium: false,
		color: '#f0e080',
		shape: 'shield',
	},
];

// T2 Rare (4 towers)
export const RARE_TOWERS: TowerDef[] = [
	{
		id: 'twin_archer',
		name: '쌍궁 탑',
		type: 'twin_archer',
		tier: 2,
		stats: { damage: 25, range: 4, attackSpeed: 2.0 },
		cost: 10,
		element: 'neutral',
		isPremium: false,
		color: '#c8a04a',
		shape: 'star',
	},
	{
		id: 'disruptor',
		name: '눈보라 탑',
		type: 'disruptor',
		tier: 2,
		stats: {
			damage: 15,
			range: 5,
			attackSpeed: 1.2,
			special: 'slow_50%_splash',
		},
		cost: 20,
		element: 'water',
		isPremium: false,
		color: '#5bc8e8',
		shape: 'star',
	},
	{
		id: 'nova_cannon',
		name: '공성 대포',
		type: 'nova_cannon',
		tier: 2,
		stats: { damage: 60, range: 3, attackSpeed: 0.4, special: 'splash' },
		cost: 10,
		element: 'fire',
		isPremium: false,
		color: '#8b4513',
		shape: 'star',
	},
	{
		id: 'fortress',
		name: '수호 탑',
		type: 'fortress',
		tier: 2,
		stats: {
			damage: 15,
			range: 3,
			attackSpeed: 1.0,
			special: 'stun_aoe',
		},
		cost: 20,
		element: 'neutral',
		isPremium: false,
		color: '#f0e080',
		shape: 'star',
	},
];

// T3 Heroic (4 towers)
export const HEROIC_TOWERS: TowerDef[] = [
	{
		id: 'stasis_field',
		name: '빙하 제단',
		type: 'stasis_field',
		tier: 3,
		stats: {
			damage: 0,
			range: 3,
			attackSpeed: 0,
			special: 'slow_30%_aoe',
		},
		cost: 20,
		element: 'water',
		isPremium: false,
		color: '#a8def0',
		shape: 'shield',
	},
	{
		id: 'flame_tower',
		name: '화염 탑',
		type: 'flame_tower',
		tier: 3,
		stats: { damage: 40, range: 3, attackSpeed: 1.5 },
		cost: 10,
		element: 'fire',
		isPremium: false,
		color: '#e85c2c',
		shape: 'diamond',
	},
	{
		id: 'wind_spire',
		name: '바람의 첨탑',
		type: 'wind_spire',
		tier: 3,
		stats: {
			damage: 20,
			range: 5,
			attackSpeed: 2.5,
		},
		cost: 10,
		element: 'lightning',
		isPremium: false,
		color: '#7ed9a0',
		shape: 'diamond',
	},
	{
		id: 'earth_golem',
		name: '대지 골렘',
		type: 'earth_golem',
		tier: 3,
		stats: { damage: 80, range: 2, attackSpeed: 0.5 },
		cost: 10,
		element: 'neutral',
		isPremium: false,
		color: '#a0856e',
		shape: 'hexagon',
	},
];

// T4 Legendary (4 towers)
export const LEGENDARY_TOWERS: TowerDef[] = [
	{
		id: 'holy_shrine',
		name: '신성 제단',
		type: 'holy_shrine',
		tier: 4,
		stats: {
			damage: 0,
			range: 3,
			attackSpeed: 0,
			special: 'stun_aoe_extended',
		},
		cost: 20,
		element: 'neutral',
		isPremium: false,
		color: '#f0d060',
		shape: 'shield',
	},
	{
		id: 'dragon_nest',
		name: '용의 둥지',
		type: 'dragon_nest',
		tier: 4,
		stats: { damage: 100, range: 4, attackSpeed: 0.8, special: 'splash' },
		cost: 10,
		element: 'fire',
		isPremium: false,
		color: '#d94040',
		shape: 'star',
	},
	{
		id: 'arcane_spire',
		name: '비전 첨탑',
		type: 'arcane_spire',
		tier: 4,
		stats: { damage: 50, range: 6, attackSpeed: 1.5 },
		cost: 10,
		element: 'lightning',
		isPremium: false,
		color: '#9060e0',
		shape: 'star',
	},
	{
		id: 'world_tree',
		name: '세계수',
		type: 'world_tree',
		tier: 4,
		stats: {
			damage: 30,
			range: 4,
			attackSpeed: 1.0,
			special: 'slow_40%_aoe',
		},
		cost: 20,
		element: 'neutral',
		isPremium: false,
		color: '#4aad5e',
		shape: 'star',
	},
];

// T5 God (2 towers)
export const GOD_TOWERS: TowerDef[] = [
	{
		id: 'celestial',
		name: '천상의 탑',
		type: 'celestial',
		tier: 5,
		stats: {
			damage: 200,
			range: 5,
			attackSpeed: 1.0,
			special: 'splash',
		},
		cost: 10,
		element: 'lightning',
		isPremium: false,
		color: '#ffe870',
		shape: 'star',
	},
	{
		id: 'divine_throne',
		name: '신의 옥좌',
		type: 'divine_throne',
		tier: 5,
		stats: {
			damage: 0,
			range: 999,
			attackSpeed: 0,
			special: 'stun_aoe_global',
		},
		cost: 20,
		element: 'neutral',
		isPremium: false,
		color: '#fff0b0',
		shape: 'star',
	},
];

export const ALL_TOWERS: TowerDef[] = [
	...BASE_TOWERS,
	...RARE_TOWERS,
	...HEROIC_TOWERS,
	...LEGENDARY_TOWERS,
	...GOD_TOWERS,
];

export function getTowersByTier(tier: number): TowerDef[] {
	return ALL_TOWERS.filter((t) => t.tier === tier);
}
