import type { UnitDef } from '../types/unit';

export const UNITS: UnitDef[] = [
	{
		id: 'scout_drone',
		name: '고블린 정찰병',
		type: 'scout_drone',
		stats: { hp: 30, speed: 3.0, armor: 0 },
		element: 'neutral',
		bounty: 5,
		isPremium: false,
	},
	{
		id: 'battle_robot',
		name: '오크 전사',
		type: 'battle_robot',
		stats: { hp: 80, speed: 1.5, armor: 5 },
		element: 'neutral',
		bounty: 12,
		isPremium: false,
	},
	{
		id: 'heavy_walker',
		name: '돌 트롤',
		type: 'heavy_walker',
		stats: { hp: 200, speed: 0.8, armor: 12 },
		element: 'fire',
		bounty: 25,
		isPremium: false,
	},
	{
		id: 'stealth_drone',
		name: '그림자 암살자',
		type: 'stealth_drone',
		stats: { hp: 50, speed: 2.5, armor: 0 },
		element: 'lightning',
		bounty: 18,
		isPremium: false,
	},
	{
		id: 'titan',
		name: '고대 드래곤',
		type: 'titan',
		stats: { hp: 500, speed: 0.5, armor: 25 },
		element: 'fire',
		bounty: 60,
		isPremium: false,
		flying: true,
	},
	// W2 — Forge
	{
		id: 'flame_imp',
		name: '화염 임프',
		type: 'flame_imp',
		stats: { hp: 80, speed: 2.2, armor: 0 },
		element: 'fire',
		bounty: 12,
		isPremium: false,
	},
	{
		id: 'lava_golem',
		name: '용암 골렘',
		type: 'lava_golem',
		stats: { hp: 900, speed: 0.6, armor: 30 },
		element: 'fire',
		bounty: 80,
		isPremium: false,
	},
	// W3 — Tower (arcane rendered as lightning element)
	{
		id: 'arcane_mage',
		name: '마법사 유닛',
		type: 'arcane_mage',
		stats: { hp: 180, speed: 1.0, armor: 5 },
		element: 'lightning',
		bounty: 30,
		isPremium: false,
		specialBehavior: 'ranged_tower_attack',
		specialParams: { range: 2, damage: 25, cooldownMs: 3000 },
	},
	{
		id: 'mana_shield',
		name: '마력 방패병',
		type: 'mana_shield',
		stats: { hp: 250, speed: 0.9, armor: 10 },
		element: 'lightning',
		bounty: 45,
		isPremium: false,
		specialBehavior: 'damage_shield',
		specialParams: { shieldHp: 300 },
	},
	// Bosses
	{
		id: 'orc_warlord',
		name: '오크 전쟁 대장',
		type: 'orc_warlord',
		stats: { hp: 4000, speed: 0.8, armor: 20 },
		element: 'neutral',
		bounty: 300,
		isPremium: false,
		bossBehaviorId: 'orc_warlord',
	},
	{
		id: 'forge_master',
		name: '단조장의 군주',
		type: 'forge_master',
		stats: { hp: 12000, speed: 0.7, armor: 35 },
		element: 'fire',
		bounty: 500,
		isPremium: false,
		bossBehaviorId: 'forge_master',
	},
	{
		id: 'corrupted_archmage',
		name: '타락한 대마법사',
		type: 'corrupted_archmage',
		stats: { hp: 25000, speed: 0.8, armor: 30 },
		element: 'lightning',
		bounty: 800,
		isPremium: false,
		bossBehaviorId: 'corrupted_archmage',
	},
];
