// FontSdfGenerator.cs — Editor stub: guides user through TMP Font Asset Creator.
//
// Phase 1 Task 7 (automatable portion — stub only).
//
// NOT automated in this task (and likely Phase 5 stretch goal):
//   Actual SDF atlas generation requires the TMP Font Asset Creator UI:
//     Window → TextMeshPro → Font Asset Creator
//   Unity 6 does not expose a fully stable scripted API for SDF generation.
//
// Required font source files (user must download and place during Phase 0b):
//   Assets/Art/Fonts/Galmuri11.ttf       — Korean pixel font (Galmuri project)
//   Assets/Art/Fonts/PressStart2P.ttf    — ASCII arcade font (Google Fonts)
//
// Character subset file (generated by Task 7 in this commit):
//   Assets/Art/Fonts/ks-x-1001-2350.txt  — ~2,350 KS X 1001 Hangul + ASCII + symbols
//
// Expected output after manual Font Asset Creator run:
//   Assets/Art/Fonts/Galmuri11-SDF.asset
//   Assets/Art/Fonts/PressStart2P-SDF.asset
//
// Usage: GLD/Regenerate TMP Fonts

using UnityEditor;
using UnityEngine;

#if UNITY_TEXTMESHPRO
using TMPro;
#endif

namespace GLD.Data.Editor
{
    public static class FontSdfGenerator
    {
        const string Galmuri11Ttf    = "Assets/Art/Fonts/Galmuri11.ttf";
        const string PressStart2PTtf = "Assets/Art/Fonts/PressStart2P.ttf";
        const string CharsetFilePath = "Assets/Art/Fonts/ks-x-1001-2350.txt";
        const string Galmuri11SdfOut = "Assets/Art/Fonts/Galmuri11-SDF.asset";
        const string PressStart2PSdfOut = "Assets/Art/Fonts/PressStart2P-SDF.asset";

        [MenuItem("GLD/Regenerate TMP Fonts")]
        public static void RegenerateTmpFontsMenu()
        {
            LogManualInstructions();
            VerifySdfAssets();
        }

        /// <summary>
        /// Logs step-by-step instructions for manual SDF generation.
        /// Called from menu and from CI verification scripts.
        /// </summary>
        public static void LogManualInstructions()
        {
            // ── Source file checks ─────────────────────────────────────────────
            bool galmuriTtfMissing    = !System.IO.File.Exists(Galmuri11Ttf);
            bool pressStartTtfMissing = !System.IO.File.Exists(PressStart2PTtf);
            bool charsetMissing       = !System.IO.File.Exists(CharsetFilePath);

            if (galmuriTtfMissing)
                Debug.LogWarning(
                    $"[GLD Fonts] Source font missing: {Galmuri11Ttf}\n" +
                    "Download Galmuri11 from https://github.com/quiple/galmuri and place the .ttf here.");

            if (pressStartTtfMissing)
                Debug.LogWarning(
                    $"[GLD Fonts] Source font missing: {PressStart2PTtf}\n" +
                    "Download Press Start 2P from https://fonts.google.com/specimen/Press+Start+2P " +
                    "and place the .ttf here.");

            if (charsetMissing)
                Debug.LogWarning(
                    $"[GLD Fonts] Character subset file missing: {CharsetFilePath}\n" +
                    "This file should have been created by Phase 1 Task 7. Check your git state.");

            // ── Instructions ──────────────────────────────────────────────────
            Debug.Log(
                "[GLD Fonts] TMP Font Asset Creator must be opened manually.\n\n" +
                "=== Galmuri11 (Korean + ASCII) ===\n" +
                "  Window → TextMeshPro → Font Asset Creator\n" +
                $"  Source Font File : {Galmuri11Ttf}\n" +
                "  Atlas Resolution : 2048 × 2048\n" +
                "  Character Set    : Characters from File\n" +
                $"  Character File   : {CharsetFilePath}\n" +
                "  Render Mode      : SDFAA  (or SDF32 for highest quality)\n" +
                "  Padding          : 5\n" +
                "  Click Generate Font Atlas, then Save As:\n" +
                $"    → {Galmuri11SdfOut}\n\n" +
                "=== Press Start 2P (ASCII only) ===\n" +
                "  Window → TextMeshPro → Font Asset Creator\n" +
                $"  Source Font File : {PressStart2PTtf}\n" +
                "  Atlas Resolution : 512 × 512\n" +
                "  Character Set    : ASCII\n" +
                "  Render Mode      : SDFAA\n" +
                "  Padding          : 5\n" +
                "  Click Generate Font Atlas, then Save As:\n" +
                $"    → {PressStart2PSdfOut}\n\n" +
                "After saving both assets, re-run GLD/Regenerate TMP Fonts to verify.");
        }

        /// <summary>
        /// Asserts presence of generated SDF assets. Warns if missing.
        /// </summary>
        public static void VerifySdfAssets()
        {
#if UNITY_TEXTMESHPRO
            if (AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(Galmuri11SdfOut) == null)
                Debug.LogWarning(
                    $"[GLD Fonts] Galmuri11-SDF.asset not found at '{Galmuri11SdfOut}'. " +
                    "Run Window → TextMeshPro → Font Asset Creator and save the output there.");
            else
                Debug.Log($"[GLD Fonts] ✓ Galmuri11-SDF.asset found at '{Galmuri11SdfOut}'.");

            if (AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(PressStart2PSdfOut) == null)
                Debug.LogWarning(
                    $"[GLD Fonts] PressStart2P-SDF.asset not found at '{PressStart2PSdfOut}'. " +
                    "Run Window → TextMeshPro → Font Asset Creator and save the output there.");
            else
                Debug.Log($"[GLD Fonts] ✓ PressStart2P-SDF.asset found at '{PressStart2PSdfOut}'.");
#else
            Debug.Log("[GLD Fonts] TextMeshPro package not detected. Install via Package Manager to verify SDF assets.");
#endif
        }
    }
}
