// TokensUssGenerator.cs — Editor tool: emits Assets/UI/Styles/tokens.uss from
// DesignTokensSO, containing CSS custom properties (USS variables) for Unity UI.
//
// Phase 1 Task 8.
//
// Output format:
//   :root {
//       --color-accent: #c8a04a;
//       --color-panel: #2a2010;
//       ...
//       --space-xs: 4px;
//       ...
//   }
//
// tokens.uss is gitignored (regenerated) — add to .gitignore if not present.
//
// Usage:
//   Interactive : GLD/Generate tokens.uss
//   Batch / CI  : TokensUssGenerator.Generate()
//   Auto-hook   : Called by JsonToSOImporter.ImportAll after SaveAll()

using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace GLD.Data.Editor
{
    public static class TokensUssGenerator
    {
        const string SOPath     = "Assets/Data/DesignTokens.asset";
        const string OutputPath = "Assets/UI/Styles/tokens.uss";

        [MenuItem("GLD/Generate tokens.uss")]
        public static void GenerateMenu()
        {
            Generate();
            EditorUtility.DisplayDialog("GLD Tokens", $"tokens.uss generated at {OutputPath}", "OK");
        }

        /// <summary>
        /// Generates tokens.uss from DesignTokensSO. Safe to call from CI / batch.
        /// Returns false (with a warning) when the SO asset is not yet imported.
        /// </summary>
        public static bool Generate()
        {
            var so = AssetDatabase.LoadAssetAtPath<GLD.Data.DesignTokensSO>(SOPath);
            if (so == null)
            {
                Debug.LogWarning(
                    $"[GLD Tokens] DesignTokensSO not found at '{SOPath}'. " +
                    "Run GLD/Import Shared Data first to create the ScriptableObject.");
                return false;
            }

            string uss = BuildUss(so);

            // Ensure output directory exists.
            string dir = Path.GetDirectoryName(OutputPath);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(OutputPath, uss, Encoding.UTF8);
            AssetDatabase.ImportAsset(OutputPath);

            Debug.Log($"[GLD Tokens] tokens.uss written to '{OutputPath}'.");
            return true;
        }

        // ── USS builder ────────────────────────────────────────────────────────

        static string BuildUss(GLD.Data.DesignTokensSO so)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* tokens.uss — AUTO-GENERATED by TokensUssGenerator.cs. DO NOT EDIT. */");
            sb.AppendLine("/* Re-generate: GLD/Generate tokens.uss  (or GLD/Import Shared Data) */");
            sb.AppendLine();
            sb.AppendLine(":root {");

            // ── Palette / Core colors ─────────────────────────────────────────
            var core = so.palette.core;
            AppendColor(sb, "color-accent",         core.accent);
            AppendColor(sb, "color-armor-pierce",   core.armorPierce);
            AppendColor(sb, "color-bg",             core.bg);
            AppendColor(sb, "color-border",         core.border);
            AppendColor(sb, "color-boss-phase1",    core.bossPhase1);
            AppendColor(sb, "color-danger",         core.danger);
            AppendColor(sb, "color-gold",           core.gold);
            AppendColor(sb, "color-grade-unique",   core.gradeUnique);
            AppendColor(sb, "color-info",           core.info);
            AppendColor(sb, "color-panel",          core.panel);
            AppendColor(sb, "color-success",        core.success);
            AppendColor(sb, "color-text",           core.text);
            AppendColor(sb, "color-text-secondary", core.textSecondary);
            AppendColor(sb, "color-tier-bright",    core.tierBright);

            // ── Palette / State ───────────────────────────────────────────────
            var state = so.palette.state;
            AppendColor(sb, "state-disabled-bg", state.disabledBg);
            AppendColor(sb, "state-disabled-fg", state.disabledFg);
            AppendColor(sb, "state-focus",       state.focus);
            AppendColor(sb, "state-hover",       state.hover);
            AppendColor(sb, "state-pressed",     state.pressed);
            AppendColor(sb, "state-warning",     state.warning);

            // ── Palette / Surface ─────────────────────────────────────────────
            var surf = so.palette.surface;
            AppendColor(sb, "surface-bg",             surf.bg);
            AppendColor(sb, "surface-panel",          surf.panel);
            AppendColor(sb, "surface-panel-elevated", surf.panelElevated);
            AppendColor(sb, "surface-panel-sunken",   surf.panelSunken);

            // Surface alpha sub-tokens
            var alpha = surf.alpha;
            AppendColor(sb, "surface-alpha-accent20",     alpha.accent20);
            AppendColor(sb, "surface-alpha-bg76",         alpha.bg76);
            AppendColor(sb, "surface-alpha-bg80",         alpha.bg80);
            AppendColor(sb, "surface-alpha-bg95",         alpha.bg95);
            AppendColor(sb, "surface-alpha-danger20",     alpha.danger20);
            AppendColor(sb, "surface-alpha-overlay60",    alpha.overlay60);
            AppendColor(sb, "surface-alpha-overlay70",    alpha.overlay70);
            AppendColor(sb, "surface-alpha-overlay-dark", alpha.overlayDark);
            AppendColor(sb, "surface-alpha-overlay-heavy",alpha.overlayHeavy);
            AppendColor(sb, "surface-alpha-panel70",      alpha.panel70);
            AppendColor(sb, "surface-alpha-panel85",      alpha.panel85);
            AppendColor(sb, "surface-alpha-panel90",      alpha.panel90);
            AppendColor(sb, "surface-alpha-panel92",      alpha.panel92);
            AppendColor(sb, "surface-alpha-panel95",      alpha.panel95);
            AppendColor(sb, "surface-alpha-panel96",      alpha.panel96);

            // ── Palette / Element colors ──────────────────────────────────────
            var elem = so.palette.element;
            AppendColor(sb, "elem-earth-primary",     elem.earth.primary);
            AppendColor(sb, "elem-earth-glow",        elem.earth.glow);
            AppendColor(sb, "elem-fire-primary",      elem.fire.primary);
            AppendColor(sb, "elem-fire-glow",         elem.fire.glow);
            AppendColor(sb, "elem-lightning-primary", elem.lightning.primary);
            AppendColor(sb, "elem-lightning-glow",    elem.lightning.glow);
            AppendColor(sb, "elem-neutral-primary",   elem.neutral.primary);
            AppendColor(sb, "elem-neutral-glow",      elem.neutral.glow);
            AppendColor(sb, "elem-water-primary",     elem.water.primary);
            AppendColor(sb, "elem-water-glow",        elem.water.glow);

            // ── Palette / Tier colors ─────────────────────────────────────────
            if (so.palette.tier != null)
            {
                foreach (var tier in so.palette.tier)
                {
                    AppendColor(sb, $"tier-{tier.tier}-primary", tier.primary);
                    AppendColor(sb, $"tier-{tier.tier}-bright",  tier.bright);
                    AppendColor(sb, $"tier-{tier.tier}-dark",    tier.dark);
                }
            }

            // ── Overlay dim ───────────────────────────────────────────────────
            var od = so.overlayDim;
            AppendColor(sb, "overlay-dim-cinematic", od.cinematic);
            AppendColor(sb, "overlay-dim-default",   od.default_);
            AppendColor(sb, "overlay-dim-heavy",     od.heavy);
            AppendColor(sb, "overlay-dim-soft",      od.soft);

            // ── Spacing ───────────────────────────────────────────────────────
            var spc = so.spacing;
            AppendPx(sb, "space-xs",   spc.xs);
            AppendPx(sb, "space-sm",   spc.sm);
            AppendPx(sb, "space-md",   spc.md);
            AppendPx(sb, "space-lg",   spc.lg);
            AppendPx(sb, "space-xl",   spc.xl);
            AppendPx(sb, "space-2xl",  spc.xxl);
            AppendPx(sb, "space-3xl",  spc.xxxl);

            // ── Radius ────────────────────────────────────────────────────────
            var rad = so.radius;
            AppendPx(sb, "radius-none", rad.none);
            AppendPx(sb, "radius-xs",   rad.xs);
            AppendPx(sb, "radius-sm",   rad.sm);
            AppendPx(sb, "radius-md",   rad.md);
            AppendPx(sb, "radius-lg",   rad.lg);
            AppendPx(sb, "radius-xl",   rad.xl);
            AppendPx(sb, "radius-pill", rad.pill);

            // ── Z-index ───────────────────────────────────────────────────────
            var zi = so.zIndex;
            AppendInt(sb, "z-board",    zi.board);
            AppendInt(sb, "z-hud",      zi.hud);
            AppendInt(sb, "z-floating", zi.floating);
            AppendInt(sb, "z-overlay",  zi.overlay);
            AppendInt(sb, "z-modal",    zi.modal);
            AppendInt(sb, "z-toast",    zi.toast);

            // ── Motion durations ──────────────────────────────────────────────
            var dur = so.motion.duration;
            AppendMs(sb, "motion-duration-fast",      dur.fast);
            AppendMs(sb, "motion-duration-base",      dur.base_);
            AppendMs(sb, "motion-duration-slow",      dur.slow);
            AppendMs(sb, "motion-duration-cinematic", dur.cinematic);

            // ── Motion easing / presets ──────────────────────────────────────
            var easing = so.motion.easing;
            AppendStr(sb, "motion-easing-standard",   easing.standard);
            AppendStr(sb, "motion-easing-emphatic",   easing.emphatic);
            AppendStr(sb, "motion-easing-decelerate", easing.decelerate);
            AppendStr(sb, "motion-easing-stepwise",   easing.stepwise);

            var preset = so.motion.preset;
            AppendStr(sb, "motion-preset-interactive", preset.interactive);
            AppendStr(sb, "motion-preset-ui",          preset.ui);
            AppendStr(sb, "motion-preset-overlay",     preset.overlay);
            AppendStr(sb, "motion-preset-punch",       preset.punch);
            AppendStr(sb, "motion-preset-cinematic",   preset.cinematic);

            // ── Elevation ────────────────────────────────────────────────────
            var elev = so.elevation;
            AppendStr(sb, "elevation-0", elev.e0);
            AppendStr(sb, "elevation-1", elev.e1);
            AppendStr(sb, "elevation-2", elev.e2);
            AppendStr(sb, "elevation-3", elev.e3);
            AppendStr(sb, "elevation-4", elev.e4);

            // ── Font families ─────────────────────────────────────────────────
            var ff = so.fontFamily;
            AppendStr(sb, "font-family-display", ff.display);
            AppendStr(sb, "font-family-pixel",   ff.pixel);

            // ── Typography ───────────────────────────────────────────────────
            if (so.typography != null)
            {
                foreach (var type in so.typography)
                {
                    if (string.IsNullOrEmpty(type.key))
                        continue;

                    var key = ToCssKey(type.key);
                    AppendStr(sb, $"type-{key}-family", type.family);
                    AppendStr(sb, $"type-{key}-size", type.size);
                    AppendFloat(sb, $"type-{key}-line-height", type.lineHeight);
                    AppendInt(sb, $"type-{key}-weight", type.weight);
                }
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── Append helpers ─────────────────────────────────────────────────────

        static void AppendColor(StringBuilder sb, string key, string value)
        {
            if (!string.IsNullOrEmpty(value))
                sb.AppendLine($"    --{key}: {value};");
        }

        static void AppendPx(StringBuilder sb, string key, int value)
        {
            sb.AppendLine($"    --{key}: {value}px;");
        }

        static void AppendMs(StringBuilder sb, string key, int value)
        {
            sb.AppendLine($"    --{key}: {value}ms;");
        }

        static void AppendInt(StringBuilder sb, string key, int value)
        {
            sb.AppendLine($"    --{key}: {value};");
        }

        static void AppendFloat(StringBuilder sb, string key, float value)
        {
            sb.AppendLine($"    --{key}: {value.ToString(System.Globalization.CultureInfo.InvariantCulture)};");
        }

        static void AppendStr(StringBuilder sb, string key, string value)
        {
            if (!string.IsNullOrEmpty(value))
                sb.AppendLine($"    --{key}: {value};");
        }

        static string ToCssKey(string key)
        {
            var sb = new StringBuilder();
            for (var i = 0; i < key.Length; i++)
            {
                var c = key[i];
                if (char.IsUpper(c))
                {
                    if (i > 0)
                        sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                }
                else if (char.IsLetterOrDigit(c))
                    sb.Append(char.ToLowerInvariant(c));
                else
                    sb.Append('-');
            }
            return sb.ToString();
        }
    }
}
